# Generated by Django 4.1.3 on 2022-11-06 02:36

import detect.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detect', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(storage=detect.models.OverwriteStorage(), upload_to=detect.models.rename_path),
        ),
    ]
